### PR TITLE
fix shrinkwrap and clean up docs

### PR DESCRIPTION
**Pull request by rmg**
Addresses a couple bugs reported as comments on #56.

### CODE REVIEW

**Comment by sam-github** [comment]
can you add docs for slt-release, too, please

**Comment by rmg** [comment]
This PR doesn't affect `slt-release`, so I'm not sure what you want added. The `slt-release -h` output is also already current.

**Comment by sam-github** [comment]
slt-release docs are not current - they don't mention the new behaviour you added to merge back to master without merging shrinkwrap

`slt -h` and the README doesn't mention `slt shrinkwrap` at all (unless that changed in this PR, but I see no signs of it in the diff)

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Comment by rmg** [comment]
@slnode test please

**Pull request merged**
