### PR TITLE
Support maintenance releases, drop production

### LINKED ISSUE #22: Handle empty changelog after a release from an older branch
Today, I made three releases of loopback-boot:

 - [v2.6.2](https://github.com/strongloop/loopback-boot/releases/tag/v2.6.2) publishing one commit
 - [v1.1.2](https://github.com/strongloop/loopback-boot/releases/tag/v1.1.2) publishing a back-port of the commit above
 - [v2.6.3](https://github.com/strongloop/loopback-boot/releases/tag/v2.6.3) to fix the README on npmjs.org

The release `v1.1.2` was made via `npm release patch && npm publish`, both `v2.6.2` and `v2.6.3` were made using `slt-release patch`.

**Actual behaviour**

The changelog generated for `v2.6.3` seems to contain all commits from the master after 1.x branch was forked.

**Expected behaviour**

The changelog generated for `v2.6.3` is empty.

/to @sam-github @rmg do you happen to know where to start investigating this problem?

### PR DESCRIPTION
**Pull request by rmg**
It is now possible to cut a release from a non-master branch and
maintain multiple release branches in parallel, such a 1.x for
backporting and releasing fixes after 2.0.0 has been released from
master.

Releases are marked with annotated tags which contain the release
changelog. If releasing from the head of a branch, that branch is
fast-forwarded to the release commit.

If a commit or ref other than HEAD is specified as the commit to base
the release on, the release commit is NOT merged back into the current
branch.

slt-release-start and slt-release-finish have been removed since the
amount of state that must be carried between them to support this
workflow makes it easier to make a mistake than not.

@sam-github this is what we discussed in the hangout

@kraman this will allow us to delete the 2.x branch on strong-pm and replace it (in purpose) with a 1.x branch for 

@bajtos this doesn't fix #22 directly, but it does solve part of the problem with releasing from maintenance release branches.

### CODE REVIEW

**Comment by bajtos** [comment]
> drop production
> branch is fast-forwarded to the release commit.

:+1: :heavy_multiplication_x: :100:

> this doesn't fix #22 directly, but it does solve part of the problem with releasing from maintenance release branches.

I am confused. If this does not fix #22, then it means that the generated changelog mixes commits and/or versions (tags) from both `1.x` and `master` (2.x) branches, is that correct? And is that intended? 

I am ok with leaving a fix for the above out of scope of this patch, I just want to clarify what is the expected behaviour.

**Comment by bajtos** [comment]
The code looks reasonable, although I did not try to understand it fully.

**Comment by rmg** [comment]
What I meant is it is this is related to #22 because it is adding support to `slt-release` for the scenario which causes the changelog problem. In other words it makes fixing #22 even more important.

**Comment by sam-github** [comment]
Looks good in principle, didn't have a chance to try it.

If doesn't do anything different from before in the "normal" case, right?

Would be easier to confirm the above if the refactor/merge of the two pieces had been one commit, and the feature another.

**Comment by rmg** [comment]
@sam-github I did it as one commit because the merging makes more sense to do first from a review perspective, but is only justified overall by the changes introduced by the refactor, so putting them in opposite order just felt like bad story telling. I'm going to have to rebase anyway, so I'll spit the commit when I do that.

**Comment by rmg** [comment]
I've decided that supporting specifying a commit to release from without checking out that commit (as a branch) is simply too error prone to support. The argument is now ignored, and additionally if a detached HEAD is detected it is considered a fatal error.

In the process I re-built the branch as a series of commits with an eye toward reduced code churn, so I think you'll find the current patch set **much** easier to review.

**Comment by sam-github** [comment]
LGTM

**Comment by sam-github** [comment]
Oh, and yes, was really easy to follow along with the changes.

**Comment by rmg** [comment]
Should be available on staging soon as 1.6.something by the time anyone reads this comment. Give it a spin. When it gets released it will be as 2.0.0.

**Comment by rmg** [comment]
Released as v2.0.0 on npmjs.org

**Pull request merged**
