### PR TITLE
Add 'use strict' to modules

### PR DESCRIPTION
**Pull request by kjdelisle**
connected to https://github.com/strongloop-internal/scrum-nodeops/issues/1596

### CODE REVIEW

**Comment by kjdelisle** [comment]
@sam-github @crandmck PTAL

**Comment by sam-github** [comment]
lgtm

**Comment by crandmck** [comment]
@kjdelisle Does this impact documentation in some way?  If so, how?  Or was I perhaps mentioned in error...?

**Comment by crandmck** [comment]
> I noticed that you had changed the tag to #review, ...
Hm, that is really weird.  I didn't do that... I wonder if there is a bot or script or something that uses my account?  

@rmg: Al Tsang used to have something like that; did it get transferred to my account somehow?   Is there some other likely explanation? Or shall we chalk it up to gremlins?

**Comment by rmg** [comment]
It is probably for the same reason as when Al got credited. I think Waffle cycles through the the tokens it has access to when making API calls so that it doesn't exceed any per-account limits. Or something similarly weird.

**Pull request merged**
