### PR TITLE
strip test folder from releases

### PR DESCRIPTION
**Pull request by rmg**
@chandadharap @sam-github @kraman here's a start on what was discussed. Can you add any additional requirements here?

### CODE REVIEW

**Comment by sam-github** [comment]
That is the default of npm publish already, to use .gitignore if there is no .npmignore.

`echo test > .npmignore` might be better. Assuming all test code was in `test/`.

**Comment by rmg** [comment]
Both .npmignore and .gitignore can be used to "ignore" files that are part of the repo. Doing `echo test > .npmignore` will do the wrong thing in cases that I personally care about:
 * if there is no .npmignore it will suppress reading of .gitignore
 * if there is a .npmignore it will remove the existing entries

Scenarios where those would happen are packages like Arc that have large amounts of design artifacts that are "source" for assets that are "built" during publish (image compositing, svg rendering, scss rendering, JS/CSS minifications, etc.).

**Comment by kraman** [comment]
Not sure its needed but would you want to strip test dependencies from package.json?

**Comment by rmg** [comment]
@kraman do you mean delete the `devDependencies` property?

**Comment by chandadharap** [comment]
Looks good. I don't suppose we want to scan or Create Commons files and FB copyrights and war? We spoke about this post  TOB.?

**Pull request merged**
